import { QspFrame } from './parser';

export class QspPromptInjector {
  private baseRules: string;

  constructor() {
    this.baseRules =
      "Quantum Semantic Protocol (QSP) 2.0 규칙을 반드시 준수하여 에이전트 간 메모리 상태를 공유하십시오.\n" +
      "당신의 통신 액터 식별자는 '[AGENT_NAME]' 입니다.\n" +
      "모든 상태 변환 완료 후 대화 말미에 반드시 아래 포맷의 QSP 한 줄을 덧붙이십시오.\n" +
      "포맷: ACT([AGENT_NAME])->MUT(대상_컴포넌트:이전_상태->이후_상태)->OBJ(대상_컴포넌트)->STATE(success)->SEV(medium)->TS([TIMESTAMP])\n" +
      "예시: ACT(ag-mac)->MUT(battery:ok->low)->OBJ(battery)->STATE(success)->SEV(medium)->TS(1779537280)\n";
  }

  public getSystemPrompt(agentType: string, agentName: string): string {
    let prompt = this.baseRules
      .replace(/\[AGENT_NAME\]/g, agentName)
      .replace('[TIMESTAMP]', Math.floor(Date.now() / 1000).toString());

    const lowerType = agentType.toLowerCase();
    if (lowerType === 'claude') {
      prompt += "XML 또는 마크다운 태그를 포함하지 말고 XML 스타일 블록 없이 순수 QSP 한 줄만 텍스트 끝에 작성해 주세요.";
    } else if (lowerType === 'gpt') {
      prompt += "출력 텍스트 마지막 줄에 정확히 'QSP: ' 접두사 뒤에 기입해 주세요.";
    }
    return prompt;
  }
}

export class FuzzyQspParser {
  /**
   * Parses and repairs incomplete or broken QSP DSL generated by smaller LLMs.
   */
  public static parseFuzzyDsl(dslStr: string): QspFrame {
    const normalized = dslStr.trim();

    const extractParam = (key: string, defaultValue = 'unknown'): string => {
      // Matches KEY(content) or key(content) tolerating unclosed parenthesis at the end
      const pattern = new RegExp(`${key}\\s*\\(\\s*([^)]*?)\\s*(?:\\)|$)`, 'i');
      const match = pattern.exec(normalized);
      return match ? match[1].trim() : defaultValue;
    };

    const actor = extractParam('ACT', 'unknown');
    let obj = extractParam('OBJ', 'unknown');
    const state = extractParam('STATE', 'success');
    const severity = extractParam('SEV', 'medium');

    const mutVal = extractParam('MUT', '');
    let mutationFrom = 'unknown';
    let mutationTo = 'unknown';

    if (mutVal.includes(':')) {
      const parts = mutVal.split(':');
      const transition = parts.slice(1).join(':');
      if (transition.includes('->')) {
        const [mFrom, mTo] = transition.split('->');
        mutationFrom = mFrom.trim();
        mutationTo = mTo.trim();
        // Remove unclosed brackets and arrow prefix if any
        mutationTo = mutationTo.replace(/->?[A-Z]+\(.*/i, '').trim();
      }
    } else if (mutVal.includes('->')) {
      const [mFrom, mTo] = mutVal.split('->');
      mutationFrom = mFrom.trim();
      mutationTo = mTo.trim();
      mutationTo = mutationTo.replace(/->?[A-Z]+\(.*/i, '').trim();
    }

    if (obj === 'unknown' && mutVal.includes(':')) {
      obj = mutVal.split(':')[0].trim();
    }

    const resolvesStr = extractParam('RESOLVE', '');
    const resolves = resolvesStr
      ? resolvesStr
          .split(',')
          .map((r) => r.trim())
          .filter(Boolean)
      : [];

    const emotions: Record<string, number> = {};
    const affStr = extractParam('AFF', '');
    if (affStr) {
      for (const item of affStr.split(',')) {
        if (item.includes(':')) {
          const [k, v] = item.split(':');
          const val = parseFloat(v.trim());
          if (!isNaN(val)) {
            emotions[k.trim()] = val;
          }
        }
      }
    }

    const tsStr = extractParam('TS', '');
    const timestamp = /^\d+$/.test(tsStr) ? parseInt(tsStr, 10) : Math.floor(Date.now() / 1000);

    const meta = extractParam('META', '') || null;

    return new QspFrame({
      actor,
      targetObject: obj,
      mutationFrom,
      mutationTo,
      resolves,
      state,
      severity,
      emotions,
      meta,
      timestamp,
    });
  }
}
