# -*- coding: utf-8 -*-
"""
QSP Core Prompt Injector & Fuzzy Parser
Provides robust system prompt customization for LLMs (Claude, GPT, Llama) 
and structural resilience for repairing partially broken QSP DSL outputs.
"""

import re
import time
from typing import Dict, Any, Optional
from qsp_core.parser import QspFrame

class QspPromptInjector:
    """
    QspPromptInjector handles system prompt customization for heterogeneous LLMs (Claude, GPT, Llama).
    Injects optimal few-shot rules to force AIs to communicate using QSP.
    """
    def __init__(self):
        self.base_rules = (
            "Quantum Semantic Protocol (QSP) 2.0 규칙을 반드시 준수하여 에이전트 간 메모리 상태를 공유하십시오.\n"
            "당신의 통신 액터 식별자는 '[AGENT_NAME]' 입니다.\n"
            "모든 상태 변환 완료 후 대화 말미에 반드시 아래 포맷의 QSP 한 줄을 덧붙이십시오.\n"
            "포맷: ACT([AGENT_NAME])->MUT(대상_컴포넌트:이전_상태->이후_상태)->OBJ(대상_컴포넌트)->STATE(success)->SEV(medium)->TS([TIMESTAMP])\n"
            "예시: ACT(ag-mac)->MUT(battery:ok->low)->OBJ(battery)->STATE(success)->SEV(medium)->TS(1779537280)\n"
        )

    def get_system_prompt(self, agent_type: str, agent_name: str) -> str:
        prompt = self.base_rules.replace("[AGENT_NAME]", agent_name).replace("[TIMESTAMP]", str(int(time.time())))
        if agent_type.lower() == "claude":
            prompt += "XML 또는 마크다운 태그를 포함하지 말고 XML 스타일 블록 없이 순수 QSP 한 줄만 텍스트 끝에 작성해 주세요."
        elif agent_type.lower() == "gpt":
            prompt += "출력 텍스트 마지막 줄에 정확히 'QSP: ' 접두사 뒤에 기입해 주세요."
        return prompt


class FuzzyQspParser:
    """
    FuzzyQspParser provides maximum structural resilience, 
    parsing and repairing incomplete or broken QSP DSL generated by smaller LLMs.
    """
    @staticmethod
    def parse_fuzzy_dsl(dsl_str: str) -> QspFrame:
        # 1. Normalize case and spaces
        normalized = dsl_str.strip()
        
        # 2. Extract elements with case-insensitive robust regexes
        def extract_param(key: str, default: str = "unknown") -> str:
            # Matches KEY(content) or key(content) tolerating unclosed parenthesis at the end
            pattern = re.compile(rf"{key}\s*\(\s*([^)]*?)\s*(?:\)|$)", re.IGNORECASE)
            match = pattern.search(normalized)
            return match.group(1).strip() if match else default

        actor = extract_param("ACT", "unknown")
        obj = extract_param("OBJ", "unknown")
        state = extract_param("STATE", "success")
        severity = extract_param("SEV", "medium")
        
        # Extract MUT transition logic
        mut_val = extract_param("MUT", "")
        mutation_from = "unknown"
        mutation_to = "unknown"
        
        if ":" in mut_val:
            _, transition = mut_val.split(":", 1)
            if "->" in transition:
                mutation_from, mutation_to = transition.split("->", 1)
                mutation_from = mutation_from.strip()
                mutation_to = mutation_to.strip()
                # Remove unclosed brackets and arrow prefix if any
                mutation_to = re.sub(r"->?[A-Z]+\(.*", "", mutation_to).strip()
        elif "->" in mut_val:
            # Fallback if no colon exists
            mutation_from, mutation_to = mut_val.split("->", 1)
            mutation_from = mutation_from.strip()
            mutation_to = mutation_to.strip()
            mutation_to = re.sub(r"->?[A-Z]+\(.*", "", mutation_to).strip()

        # Target object fuzzy lookup
        if obj == "unknown" and ":" in mut_val:
            obj = mut_val.split(":", 1)[0].strip()

        # Parse resolves (RESOLVE)
        resolves_str = extract_param("RESOLVE", "")
        resolves = [r.strip() for r in resolves_str.split(",") if r.strip()] if resolves_str else []

        # Parse emotions (AFF)
        emotions = {}
        aff_str = extract_param("AFF", "")
        if aff_str:
            for item in aff_str.split(","):
                if ":" in item:
                    k, v = item.split(":", 1)
                    try:
                        emotions[k.strip()] = float(v.strip())
                    except ValueError:
                        pass

        # Parse timestamp (TS)
        ts_str = extract_param("TS", "")
        timestamp = int(ts_str) if ts_str.isdigit() else int(time.time())

        # Extract meta (META)
        meta = extract_param("META", None)

        return QspFrame(
            actor=actor,
            target_object=obj,
            mutation_from=mutation_from,
            mutation_to=mutation_to,
            resolves=resolves,
            state=state,
            severity=severity,
            emotions=emotions,
            meta=meta,
            timestamp=timestamp
        )
